### PR TITLE
Add a skip-to-main content link

### PR DESCRIPTION
**Pull request by ijdickinson**
Support keyboard navigation by adding a skip-to-main-content link

### CODE REVIEW

**Comment by joescottdave** [comment]
Not seeing the skip to main content stuff here ?

**Comment by ijdickinson** [comment]
@joescottdave The page template and partial are being pulled from `lr_common_styles`, so the change is to pull that dependency from upstream

**Review by joescottdave — APPROVED** [review]
👍

**Review by bogdanadrianmarc — APPROVED** [review]
lgtm

**Pull request merged**
