### PR TITLE
Update to Prometheus 4.0 and revise readme

### PR DESCRIPTION
**Pull request by ijdickinson**
This commit addreses two related cleanup tasks:

- upgrade to `prometheus-client` 4.0, which means that we can drop the
  use of the local `Prometheus::Metrics` registry
- check and revise the README, including noting the changes in
  Prometheus

### CODE REVIEW

**Review by der — APPROVED** [review]

**Review by jonrandahl — APPROVED** [review]
My only question is in `config/initializers/prometheus.rb` where on the other updated projects we've invoked the `Prometheus::Client.registry` once and passed that to the counter calls - was there any specific reason you didn't do that on this instance?

Otherwise LGTM!

**Comment by ijdickinson** [comment]
> was there any specific reason you didn't do that on this instance?

Probably something to do with being nearly midnight when I was working on it :grin:

**Comment by ijdickinson** [comment]
@jonrandahl I've made a small refactoring to improve consistency

**Review by jonrandahl — COMMENTED** [review]
LGTM!!! 😄

**Pull request merged**
