### PR TITLE
Access local gems from GPR

### PR DESCRIPTION
**Pull request by ijdickinson**
epimorphics/hmlr-linked-data#88
epimorphics/hmlr-linked-data#89

With this change, we no longer access local gem dependencies directly
via the Github repo, but instead use gems that have been published to
the Github Package Registry. This is more robust and more secure,
paricuarly when access gems that are not in public repos.

### CODE REVIEW

**Review by joescottdave — COMMENTED** [review]
Looks good, is there a particular reason for the GH action test failures here?

**Comment by ijdickinson** [comment]
> Looks good, is there a particular reason for the GH action test failures here?

Hrm, it looks like the action isn't seeing the right (or, any?) PAT to access the gems from the register. I may have to ask for help on that

**Review by bogdanadrianmarc — APPROVED** [review]
There's a fail on ECR Image upload, not sure if relevant; otherwise, lgtm 👍

**Comment by ijdickinson** [comment]
> There's a fail on ECR Image upload, not sure if relevant; 

This is just a draft PR. Using the new version of sapi-client-ruby was blocked on that being approved upstream, so in the meantime I was loading a local copy

**Comment by ijdickinson** [comment]
> There's a fail on ECR Image upload

Sorry, the previous reply was in the wrong project. This is the same problem as Joseph pointed out ... it looks like the PAT is not set up yet

**Comment by ijdickinson** [comment]
I'm re-requesting reviews, since I've had to make some additional changes while trying to resolve a build issue. Specifically:

- switched to the reusable GitHub action definitions
- updated `Makefile` and `Buildfile` to match current Epimorphics' best practices

In addition, @der added a config option to use a repository-specific access token to permit access to the GPR

**Review by joescottdave — APPROVED** [review]
Doesn't look malicious 👍

**Review by jonrandahl — APPROVED** [review]
looks good to me 👍

**Review by bogdanadrianmarc — APPROVED** [review]
Changes look good!

**Pull request merged**
